#!/usr/bin/env bash

test ! -n "${ZETS}"  && echo "ZETS not set" && exit 1;

# Count the number of non-hidden directories in the ZETS folder
current_number=$(find "${ZETS}" -type d -not -path "${ZETS}/.git*" -not -name ".*" | wc -l)

log_number=$((current_number - 1))

echo "# Paperstac Daily Log ${log_number}"
echo ""
echo '## '$(now "$*")

